// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/v1/rate-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRatesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesReq) Reset() {
	*x = GetRatesReq{}
	mi := &file_proto_v1_rate_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesReq) ProtoMessage() {}

func (x *GetRatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_rate_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesReq.ProtoReflect.Descriptor instead.
func (*GetRatesReq) Descriptor() ([]byte, []int) {
	return file_proto_v1_rate_service_proto_rawDescGZIP(), []int{0}
}

type GetRatesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradingPair   string                 `protobuf:"bytes,1,opt,name=trading_pair,json=tradingPair,proto3" json:"trading_pair,omitempty"`
	AskPrice      float64                `protobuf:"fixed64,2,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"`
	BidPrice      float64                `protobuf:"fixed64,3,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResp) Reset() {
	*x = GetRatesResp{}
	mi := &file_proto_v1_rate_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResp) ProtoMessage() {}

func (x *GetRatesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_rate_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResp.ProtoReflect.Descriptor instead.
func (*GetRatesResp) Descriptor() ([]byte, []int) {
	return file_proto_v1_rate_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatesResp) GetTradingPair() string {
	if x != nil {
		return x.TradingPair
	}
	return ""
}

func (x *GetRatesResp) GetAskPrice() float64 {
	if x != nil {
		return x.AskPrice
	}
	return 0
}

func (x *GetRatesResp) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *GetRatesResp) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HealthcheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckReq) Reset() {
	*x = HealthcheckReq{}
	mi := &file_proto_v1_rate_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckReq) ProtoMessage() {}

func (x *HealthcheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_rate_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckReq.ProtoReflect.Descriptor instead.
func (*HealthcheckReq) Descriptor() ([]byte, []int) {
	return file_proto_v1_rate_service_proto_rawDescGZIP(), []int{2}
}

type HealthcheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResp) Reset() {
	*x = HealthcheckResp{}
	mi := &file_proto_v1_rate_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResp) ProtoMessage() {}

func (x *HealthcheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_rate_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResp.ProtoReflect.Descriptor instead.
func (*HealthcheckResp) Descriptor() ([]byte, []int) {
	return file_proto_v1_rate_service_proto_rawDescGZIP(), []int{3}
}

func (x *HealthcheckResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthcheckResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_v1_rate_service_proto protoreflect.FileDescriptor

const file_proto_v1_rate_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/v1/rate-service.proto\x12\x0erateservice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vGetRatesReq\"\xa5\x01\n" +
	"\fGetRatesResp\x12!\n" +
	"\ftrading_pair\x18\x01 \x01(\tR\vtradingPair\x12\x1b\n" +
	"\task_price\x18\x02 \x01(\x01R\baskPrice\x12\x1b\n" +
	"\tbid_price\x18\x03 \x01(\x01R\bbidPrice\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x10\n" +
	"\x0eHealthcheckReq\"C\n" +
	"\x0fHealthcheckResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa8\x01\n" +
	"\vRateService\x12G\n" +
	"\bGetRates\x12\x1b.rateservice.v1.GetRatesReq\x1a\x1c.rateservice.v1.GetRatesResp\"\x00\x12P\n" +
	"\vHealthcheck\x12\x1e.rateservice.v1.HealthcheckReq\x1a\x1f.rateservice.v1.HealthcheckResp\"\x00B+Z)github.com/atadzan/grinex-rate-service/pbb\x06proto3"

var (
	file_proto_v1_rate_service_proto_rawDescOnce sync.Once
	file_proto_v1_rate_service_proto_rawDescData []byte
)

func file_proto_v1_rate_service_proto_rawDescGZIP() []byte {
	file_proto_v1_rate_service_proto_rawDescOnce.Do(func() {
		file_proto_v1_rate_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_rate_service_proto_rawDesc), len(file_proto_v1_rate_service_proto_rawDesc)))
	})
	return file_proto_v1_rate_service_proto_rawDescData
}

var file_proto_v1_rate_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v1_rate_service_proto_goTypes = []any{
	(*GetRatesReq)(nil),           // 0: rateservice.v1.GetRatesReq
	(*GetRatesResp)(nil),          // 1: rateservice.v1.GetRatesResp
	(*HealthcheckReq)(nil),        // 2: rateservice.v1.HealthcheckReq
	(*HealthcheckResp)(nil),       // 3: rateservice.v1.HealthcheckResp
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_v1_rate_service_proto_depIdxs = []int32{
	4, // 0: rateservice.v1.GetRatesResp.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: rateservice.v1.RateService.GetRates:input_type -> rateservice.v1.GetRatesReq
	2, // 2: rateservice.v1.RateService.Healthcheck:input_type -> rateservice.v1.HealthcheckReq
	1, // 3: rateservice.v1.RateService.GetRates:output_type -> rateservice.v1.GetRatesResp
	3, // 4: rateservice.v1.RateService.Healthcheck:output_type -> rateservice.v1.HealthcheckResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_rate_service_proto_init() }
func file_proto_v1_rate_service_proto_init() {
	if File_proto_v1_rate_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_rate_service_proto_rawDesc), len(file_proto_v1_rate_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_rate_service_proto_goTypes,
		DependencyIndexes: file_proto_v1_rate_service_proto_depIdxs,
		MessageInfos:      file_proto_v1_rate_service_proto_msgTypes,
	}.Build()
	File_proto_v1_rate_service_proto = out.File
	file_proto_v1_rate_service_proto_goTypes = nil
	file_proto_v1_rate_service_proto_depIdxs = nil
}
